# Generated by Django 3.1.2 on 2020-10-06 00:40

import datetime
from django.db import migrations, models
from datetime import timezone
utc = timezone.utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 0, 40, 18, 850960, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='current_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='include',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='projected_yield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rationale',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='target_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
