# Generated by Django 3.1.1 on 2020-10-09 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20201009_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'author')},
        ),
    ]
