# Generated by Django 3.1.1 on 2020-10-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201029_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='cons',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='pros',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='rationale',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
