# Generated by Django 3.1.1 on 2020-11-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201029_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='cons',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='pros',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='rationale',
            field=models.TextField(default='', max_length=250),
        ),
    ]
